#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Çok_Yönlü_Otomasyon_Programı.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="stokcari")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    partial void InsertTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void UpdateTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void DeleteTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void InsertTBL_KASALAR(TBL_KASALAR instance);
    partial void UpdateTBL_KASALAR(TBL_KASALAR instance);
    partial void DeleteTBL_KASALAR(TBL_KASALAR instance);
    partial void InsertTBL_KASAHAREKETLERİ(TBL_KASAHAREKETLERİ instance);
    partial void UpdateTBL_KASAHAREKETLERİ(TBL_KASAHAREKETLERİ instance);
    partial void DeleteTBL_KASAHAREKETLERİ(TBL_KASAHAREKETLERİ instance);
    partial void InsertTBL_CARİLER(TBL_CARİLER instance);
    partial void UpdateTBL_CARİLER(TBL_CARİLER instance);
    partial void DeleteTBL_CARİLER(TBL_CARİLER instance);
    partial void InsertTBL_CARİHAREKETLERİ(TBL_CARİHAREKETLERİ instance);
    partial void UpdateTBL_CARİHAREKETLERİ(TBL_CARİHAREKETLERİ instance);
    partial void DeleteTBL_CARİHAREKETLERİ(TBL_CARİHAREKETLERİ instance);
    partial void InsertTBL_CARİGRUPLARI(TBL_CARİGRUPLARI instance);
    partial void UpdateTBL_CARİGRUPLARI(TBL_CARİGRUPLARI instance);
    partial void DeleteTBL_CARİGRUPLARI(TBL_CARİGRUPLARI instance);
    partial void InsertTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void UpdateTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void DeleteTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Çok_Yönlü_Otomasyon_Programı.Properties.Settings.Default.stokcariConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLAR
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKGRUPLARI> TBL_STOKGRUPLARI
		{
			get
			{
				return this.GetTable<TBL_STOKGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KASALAR> TBL_KASALAR
		{
			get
			{
				return this.GetTable<TBL_KASALAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KASAHAREKETLERİ> TBL_KASAHAREKETLERİ
		{
			get
			{
				return this.GetTable<TBL_KASAHAREKETLERİ>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARİLER> TBL_CARİLER
		{
			get
			{
				return this.GetTable<TBL_CARİLER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARİHAREKETLERİ> TBL_CARİHAREKETLERİ
		{
			get
			{
				return this.GetTable<TBL_CARİHAREKETLERİ>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARİGRUPLARI> TBL_CARİGRUPLARI
		{
			get
			{
				return this.GetTable<TBL_CARİGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BANKALAR> TBL_BANKALAR
		{
			get
			{
				return this.GetTable<TBL_BANKALAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BANKAHAREKETLERİ> TBL_BANKAHAREKETLERİ
		{
			get
			{
				return this.GetTable<TBL_BANKAHAREKETLERİ>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKADURUM> VW_BANKADURUM
		{
			get
			{
				return this.GetTable<VW_BANKADURUM>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKAHAREKETLERİ> VW_BANKAHAREKETLERİ
		{
			get
			{
				return this.GetTable<VW_BANKAHAREKETLERİ>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKALİSTESİ> VW_BANKALİSTESİ
		{
			get
			{
				return this.GetTable<VW_BANKALİSTESİ>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASADURUM> VW_KASADURUM
		{
			get
			{
				return this.GetTable<VW_KASADURUM>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASAHAREKETLERİ> VW_KASAHAREKETLERİ
		{
			get
			{
				return this.GetTable<VW_KASAHAREKETLERİ>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASALİSTESİ> VW_KASALİSTESİ
		{
			get
			{
				return this.GetTable<VW_KASALİSTESİ>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KULLANICILAR> TBL_KULLANICILAR
		{
			get
			{
				return this.GetTable<TBL_KULLANICILAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _STOKBARKOD;
		
		private string _STOKKODU;
		
		private string _STOKADI;
		
		private string _STOKBİRİM;
		
		private System.Nullable<decimal> _STOKALISFİYAT;
		
		private System.Nullable<decimal> _STOKSATISFİYAT;
		
		private System.Nullable<decimal> _STOKALISKDV;
		
		private System.Nullable<decimal> _STOKSATISKDV;
		
		private System.Nullable<int> _STOKGRUPID;
		
		private System.Data.Linq.Binary _STOKRESİM;
		
		private System.Nullable<int> _STOKSAVEUSER;
		
		private System.Nullable<System.DateTime> _STOKSAVEDATE;
		
		private System.Nullable<int> _STOKEDİTUSER;
		
		private System.Nullable<System.DateTime> _STOKEDİTTİME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSTOKBARKODChanging(string value);
    partial void OnSTOKBARKODChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADIChanging(string value);
    partial void OnSTOKADIChanged();
    partial void OnSTOKBİRİMChanging(string value);
    partial void OnSTOKBİRİMChanged();
    partial void OnSTOKALISFİYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISFİYATChanged();
    partial void OnSTOKSATISFİYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISFİYATChanged();
    partial void OnSTOKALISKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISKDVChanged();
    partial void OnSTOKSATISKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISKDVChanged();
    partial void OnSTOKGRUPIDChanging(System.Nullable<int> value);
    partial void OnSTOKGRUPIDChanged();
    partial void OnSTOKRESİMChanging(System.Data.Linq.Binary value);
    partial void OnSTOKRESİMChanged();
    partial void OnSTOKSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSTOKSAVEUSERChanged();
    partial void OnSTOKSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKSAVEDATEChanged();
    partial void OnSTOKEDİTUSERChanging(System.Nullable<int> value);
    partial void OnSTOKEDİTUSERChanged();
    partial void OnSTOKEDİTTİMEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKEDİTTİMEChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBARKOD", DbType="NVarChar(30)")]
		public string STOKBARKOD
		{
			get
			{
				return this._STOKBARKOD;
			}
			set
			{
				if ((this._STOKBARKOD != value))
				{
					this.OnSTOKBARKODChanging(value);
					this.SendPropertyChanging();
					this._STOKBARKOD = value;
					this.SendPropertyChanged("STOKBARKOD");
					this.OnSTOKBARKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NVarChar(20)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this.OnSTOKADIChanging(value);
					this.SendPropertyChanging();
					this._STOKADI = value;
					this.SendPropertyChanged("STOKADI");
					this.OnSTOKADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBİRİM", DbType="NVarChar(15)")]
		public string STOKBİRİM
		{
			get
			{
				return this._STOKBİRİM;
			}
			set
			{
				if ((this._STOKBİRİM != value))
				{
					this.OnSTOKBİRİMChanging(value);
					this.SendPropertyChanging();
					this._STOKBİRİM = value;
					this.SendPropertyChanged("STOKBİRİM");
					this.OnSTOKBİRİMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISFİYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISFİYAT
		{
			get
			{
				return this._STOKALISFİYAT;
			}
			set
			{
				if ((this._STOKALISFİYAT != value))
				{
					this.OnSTOKALISFİYATChanging(value);
					this.SendPropertyChanging();
					this._STOKALISFİYAT = value;
					this.SendPropertyChanged("STOKALISFİYAT");
					this.OnSTOKALISFİYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISFİYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISFİYAT
		{
			get
			{
				return this._STOKSATISFİYAT;
			}
			set
			{
				if ((this._STOKSATISFİYAT != value))
				{
					this.OnSTOKSATISFİYATChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISFİYAT = value;
					this.SendPropertyChanged("STOKSATISFİYAT");
					this.OnSTOKSATISFİYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISKDV
		{
			get
			{
				return this._STOKALISKDV;
			}
			set
			{
				if ((this._STOKALISKDV != value))
				{
					this.OnSTOKALISKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKALISKDV = value;
					this.SendPropertyChanged("STOKALISKDV");
					this.OnSTOKALISKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISKDV
		{
			get
			{
				return this._STOKSATISKDV;
			}
			set
			{
				if ((this._STOKSATISKDV != value))
				{
					this.OnSTOKSATISKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISKDV = value;
					this.SendPropertyChanged("STOKSATISKDV");
					this.OnSTOKSATISKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKGRUPID", DbType="Int")]
		public System.Nullable<int> STOKGRUPID
		{
			get
			{
				return this._STOKGRUPID;
			}
			set
			{
				if ((this._STOKGRUPID != value))
				{
					this.OnSTOKGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._STOKGRUPID = value;
					this.SendPropertyChanged("STOKGRUPID");
					this.OnSTOKGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKRESİM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STOKRESİM
		{
			get
			{
				return this._STOKRESİM;
			}
			set
			{
				if ((this._STOKRESİM != value))
				{
					this.OnSTOKRESİMChanging(value);
					this.SendPropertyChanging();
					this._STOKRESİM = value;
					this.SendPropertyChanged("STOKRESİM");
					this.OnSTOKRESİMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEUSER", DbType="Int")]
		public System.Nullable<int> STOKSAVEUSER
		{
			get
			{
				return this._STOKSAVEUSER;
			}
			set
			{
				if ((this._STOKSAVEUSER != value))
				{
					this.OnSTOKSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEUSER = value;
					this.SendPropertyChanged("STOKSAVEUSER");
					this.OnSTOKSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKSAVEDATE
		{
			get
			{
				return this._STOKSAVEDATE;
			}
			set
			{
				if ((this._STOKSAVEDATE != value))
				{
					this.OnSTOKSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEDATE = value;
					this.SendPropertyChanged("STOKSAVEDATE");
					this.OnSTOKSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDİTUSER", DbType="Int")]
		public System.Nullable<int> STOKEDİTUSER
		{
			get
			{
				return this._STOKEDİTUSER;
			}
			set
			{
				if ((this._STOKEDİTUSER != value))
				{
					this.OnSTOKEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKEDİTUSER = value;
					this.SendPropertyChanged("STOKEDİTUSER");
					this.OnSTOKEDİTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDİTTİME", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKEDİTTİME
		{
			get
			{
				return this._STOKEDİTTİME;
			}
			set
			{
				if ((this._STOKEDİTTİME != value))
				{
					this.OnSTOKEDİTTİMEChanging(value);
					this.SendPropertyChanging();
					this._STOKEDİTTİME = value;
					this.SendPropertyChanged("STOKEDİTTİME");
					this.OnSTOKEDİTTİMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKGRUPLARI")]
	public partial class TBL_STOKGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<int> _GRUPSAVEUSER;
		
		private System.Nullable<System.DateTime> _GRUPSAVEDATE;
		
		private System.Nullable<int> _GRUPEDİTUSER;
		
		private System.Nullable<System.DateTime> _GRUPEDİTDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnGRUPSAVEUSERChanged();
    partial void OnGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPSAVEDATEChanged();
    partial void OnGRUPEDİTUSERChanging(System.Nullable<int> value);
    partial void OnGRUPEDİTUSERChanged();
    partial void OnGRUPEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPEDİTDATEChanged();
    #endregion
		
		public TBL_STOKGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> GRUPSAVEUSER
		{
			get
			{
				return this._GRUPSAVEUSER;
			}
			set
			{
				if ((this._GRUPSAVEUSER != value))
				{
					this.OnGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEUSER = value;
					this.SendPropertyChanged("GRUPSAVEUSER");
					this.OnGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPSAVEDATE
		{
			get
			{
				return this._GRUPSAVEDATE;
			}
			set
			{
				if ((this._GRUPSAVEDATE != value))
				{
					this.OnGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEDATE = value;
					this.SendPropertyChanged("GRUPSAVEDATE");
					this.OnGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDİTUSER", DbType="Int")]
		public System.Nullable<int> GRUPEDİTUSER
		{
			get
			{
				return this._GRUPEDİTUSER;
			}
			set
			{
				if ((this._GRUPEDİTUSER != value))
				{
					this.OnGRUPEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDİTUSER = value;
					this.SendPropertyChanged("GRUPEDİTUSER");
					this.OnGRUPEDİTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPEDİTDATE
		{
			get
			{
				return this._GRUPEDİTDATE;
			}
			set
			{
				if ((this._GRUPEDİTDATE != value))
				{
					this.OnGRUPEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDİTDATE = value;
					this.SendPropertyChanged("GRUPEDİTDATE");
					this.OnGRUPEDİTDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KASALAR")]
	public partial class TBL_KASALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _ACİKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKASAKODUChanging(string value);
    partial void OnKASAKODUChanged();
    partial void OnKASAADIChanging(string value);
    partial void OnKASAADIChanged();
    partial void OnACİKLAMAChanging(string value);
    partial void OnACİKLAMAChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    #endregion
		
		public TBL_KASALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this.OnKASAKODUChanging(value);
					this.SendPropertyChanging();
					this._KASAKODU = value;
					this.SendPropertyChanged("KASAKODU");
					this.OnKASAKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this.OnKASAADIChanging(value);
					this.SendPropertyChanging();
					this._KASAADI = value;
					this.SendPropertyChanged("KASAADI");
					this.OnKASAADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACİKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACİKLAMA
		{
			get
			{
				return this._ACİKLAMA;
			}
			set
			{
				if ((this._ACİKLAMA != value))
				{
					this.OnACİKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACİKLAMA = value;
					this.SendPropertyChanged("ACİKLAMA");
					this.OnACİKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KASAHAREKETLERİ")]
	public partial class TBL_KASAHAREKETLERİ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<int> _CARİID;
		
		private string _BELGENO;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private System.Nullable<System.DateTime> _TARİH;
		
		private string _GCKODU;
		
		private System.Nullable<decimal> _TUTAR;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKASAIDChanging(System.Nullable<int> value);
    partial void OnKASAIDChanged();
    partial void OnCARİIDChanging(System.Nullable<int> value);
    partial void OnCARİIDChanged();
    partial void OnBELGENOChanging(string value);
    partial void OnBELGENOChanged();
    partial void OnEVRAKTURUChanging(string value);
    partial void OnEVRAKTURUChanged();
    partial void OnEVRAKIDChanging(System.Nullable<int> value);
    partial void OnEVRAKIDChanged();
    partial void OnTARİHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARİHChanged();
    partial void OnGCKODUChanging(string value);
    partial void OnGCKODUChanged();
    partial void OnTUTARChanging(System.Nullable<decimal> value);
    partial void OnTUTARChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    #endregion
		
		public TBL_KASAHAREKETLERİ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this.OnKASAIDChanging(value);
					this.SendPropertyChanging();
					this._KASAID = value;
					this.SendPropertyChanged("KASAID");
					this.OnKASAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİID", DbType="Int")]
		public System.Nullable<int> CARİID
		{
			get
			{
				return this._CARİID;
			}
			set
			{
				if ((this._CARİID != value))
				{
					this.OnCARİIDChanging(value);
					this.SendPropertyChanging();
					this._CARİID = value;
					this.SendPropertyChanged("CARİID");
					this.OnCARİIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(50)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this.OnBELGENOChanging(value);
					this.SendPropertyChanging();
					this._BELGENO = value;
					this.SendPropertyChanged("BELGENO");
					this.OnBELGENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this.OnEVRAKTURUChanging(value);
					this.SendPropertyChanging();
					this._EVRAKTURU = value;
					this.SendPropertyChanged("EVRAKTURU");
					this.OnEVRAKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this.OnEVRAKIDChanging(value);
					this.SendPropertyChanging();
					this._EVRAKID = value;
					this.SendPropertyChanged("EVRAKID");
					this.OnEVRAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARİH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARİH
		{
			get
			{
				return this._TARİH;
			}
			set
			{
				if ((this._TARİH != value))
				{
					this.OnTARİHChanging(value);
					this.SendPropertyChanging();
					this._TARİH = value;
					this.SendPropertyChanged("TARİH");
					this.OnTARİHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKODU", DbType="NVarChar(1)")]
		public string GCKODU
		{
			get
			{
				return this._GCKODU;
			}
			set
			{
				if ((this._GCKODU != value))
				{
					this.OnGCKODUChanging(value);
					this.SendPropertyChanging();
					this._GCKODU = value;
					this.SendPropertyChanged("GCKODU");
					this.OnGCKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this.OnTUTARChanging(value);
					this.SendPropertyChanging();
					this._TUTAR = value;
					this.SendPropertyChanged("TUTAR");
					this.OnTUTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARİLER")]
	public partial class TBL_CARİLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CARİKODU;
		
		private string _CARİADI;
		
		private string _VERGİDAİRESİ;
		
		private string _VERGİNO;
		
		private System.Nullable<int> _GRUPID;
		
		private string _ULKE;
		
		private string _SEHİR;
		
		private string _İLCE;
		
		private string _ADRES;
		
		private string _TELEFON1;
		
		private string _TELEFON2;
		
		private string _FAX1;
		
		private string _FAX2;
		
		private string _WEBADRES;
		
		private string _MAILINFO;
		
		private string _YETKİLİ1;
		
		private string _YETKİLİ2;
		
		private string _YETKİLİ1EMAİLİ1;
		
		private string _YETKİLİ2EMAİLİ2;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARİKODUChanging(string value);
    partial void OnCARİKODUChanged();
    partial void OnCARİADIChanging(string value);
    partial void OnCARİADIChanged();
    partial void OnVERGİDAİRESİChanging(string value);
    partial void OnVERGİDAİRESİChanged();
    partial void OnVERGİNOChanging(string value);
    partial void OnVERGİNOChanged();
    partial void OnGRUPIDChanging(System.Nullable<int> value);
    partial void OnGRUPIDChanged();
    partial void OnULKEChanging(string value);
    partial void OnULKEChanged();
    partial void OnSEHİRChanging(string value);
    partial void OnSEHİRChanged();
    partial void OnİLCEChanging(string value);
    partial void OnİLCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTELEFON1Changing(string value);
    partial void OnTELEFON1Changed();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnFAX1Changing(string value);
    partial void OnFAX1Changed();
    partial void OnFAX2Changing(string value);
    partial void OnFAX2Changed();
    partial void OnWEBADRESChanging(string value);
    partial void OnWEBADRESChanged();
    partial void OnMAILINFOChanging(string value);
    partial void OnMAILINFOChanged();
    partial void OnYETKİLİ1Changing(string value);
    partial void OnYETKİLİ1Changed();
    partial void OnYETKİLİ2Changing(string value);
    partial void OnYETKİLİ2Changed();
    partial void OnYETKİLİ1EMAİLİ1Changing(string value);
    partial void OnYETKİLİ1EMAİLİ1Changed();
    partial void OnYETKİLİ2EMAİLİ2Changing(string value);
    partial void OnYETKİLİ2EMAİLİ2Changed();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    #endregion
		
		public TBL_CARİLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİKODU", DbType="NVarChar(30)")]
		public string CARİKODU
		{
			get
			{
				return this._CARİKODU;
			}
			set
			{
				if ((this._CARİKODU != value))
				{
					this.OnCARİKODUChanging(value);
					this.SendPropertyChanging();
					this._CARİKODU = value;
					this.SendPropertyChanged("CARİKODU");
					this.OnCARİKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİADI", DbType="NVarChar(30)")]
		public string CARİADI
		{
			get
			{
				return this._CARİADI;
			}
			set
			{
				if ((this._CARİADI != value))
				{
					this.OnCARİADIChanging(value);
					this.SendPropertyChanging();
					this._CARİADI = value;
					this.SendPropertyChanged("CARİADI");
					this.OnCARİADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGİDAİRESİ", DbType="NVarChar(50)")]
		public string VERGİDAİRESİ
		{
			get
			{
				return this._VERGİDAİRESİ;
			}
			set
			{
				if ((this._VERGİDAİRESİ != value))
				{
					this.OnVERGİDAİRESİChanging(value);
					this.SendPropertyChanging();
					this._VERGİDAİRESİ = value;
					this.SendPropertyChanged("VERGİDAİRESİ");
					this.OnVERGİDAİRESİChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGİNO", DbType="NVarChar(20)")]
		public string VERGİNO
		{
			get
			{
				return this._VERGİNO;
			}
			set
			{
				if ((this._VERGİNO != value))
				{
					this.OnVERGİNOChanging(value);
					this.SendPropertyChanging();
					this._VERGİNO = value;
					this.SendPropertyChanged("VERGİNO");
					this.OnVERGİNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPID", DbType="Int")]
		public System.Nullable<int> GRUPID
		{
			get
			{
				return this._GRUPID;
			}
			set
			{
				if ((this._GRUPID != value))
				{
					this.OnGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._GRUPID = value;
					this.SendPropertyChanged("GRUPID");
					this.OnGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULKE", DbType="NVarChar(30)")]
		public string ULKE
		{
			get
			{
				return this._ULKE;
			}
			set
			{
				if ((this._ULKE != value))
				{
					this.OnULKEChanging(value);
					this.SendPropertyChanging();
					this._ULKE = value;
					this.SendPropertyChanged("ULKE");
					this.OnULKEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHİR", DbType="NVarChar(30)")]
		public string SEHİR
		{
			get
			{
				return this._SEHİR;
			}
			set
			{
				if ((this._SEHİR != value))
				{
					this.OnSEHİRChanging(value);
					this.SendPropertyChanging();
					this._SEHİR = value;
					this.SendPropertyChanged("SEHİR");
					this.OnSEHİRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İLCE", DbType="NVarChar(30)")]
		public string İLCE
		{
			get
			{
				return this._İLCE;
			}
			set
			{
				if ((this._İLCE != value))
				{
					this.OnİLCEChanging(value);
					this.SendPropertyChanging();
					this._İLCE = value;
					this.SendPropertyChanged("İLCE");
					this.OnİLCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON1", DbType="NVarChar(16)")]
		public string TELEFON1
		{
			get
			{
				return this._TELEFON1;
			}
			set
			{
				if ((this._TELEFON1 != value))
				{
					this.OnTELEFON1Changing(value);
					this.SendPropertyChanging();
					this._TELEFON1 = value;
					this.SendPropertyChanged("TELEFON1");
					this.OnTELEFON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="NVarChar(16)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX1", DbType="NVarChar(16)")]
		public string FAX1
		{
			get
			{
				return this._FAX1;
			}
			set
			{
				if ((this._FAX1 != value))
				{
					this.OnFAX1Changing(value);
					this.SendPropertyChanging();
					this._FAX1 = value;
					this.SendPropertyChanged("FAX1");
					this.OnFAX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX2", DbType="NVarChar(16)")]
		public string FAX2
		{
			get
			{
				return this._FAX2;
			}
			set
			{
				if ((this._FAX2 != value))
				{
					this.OnFAX2Changing(value);
					this.SendPropertyChanging();
					this._FAX2 = value;
					this.SendPropertyChanged("FAX2");
					this.OnFAX2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBADRES", DbType="NVarChar(150)")]
		public string WEBADRES
		{
			get
			{
				return this._WEBADRES;
			}
			set
			{
				if ((this._WEBADRES != value))
				{
					this.OnWEBADRESChanging(value);
					this.SendPropertyChanging();
					this._WEBADRES = value;
					this.SendPropertyChanged("WEBADRES");
					this.OnWEBADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAILINFO", DbType="NVarChar(250)")]
		public string MAILINFO
		{
			get
			{
				return this._MAILINFO;
			}
			set
			{
				if ((this._MAILINFO != value))
				{
					this.OnMAILINFOChanging(value);
					this.SendPropertyChanging();
					this._MAILINFO = value;
					this.SendPropertyChanged("MAILINFO");
					this.OnMAILINFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKİLİ1", DbType="NVarChar(50)")]
		public string YETKİLİ1
		{
			get
			{
				return this._YETKİLİ1;
			}
			set
			{
				if ((this._YETKİLİ1 != value))
				{
					this.OnYETKİLİ1Changing(value);
					this.SendPropertyChanging();
					this._YETKİLİ1 = value;
					this.SendPropertyChanged("YETKİLİ1");
					this.OnYETKİLİ1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKİLİ2", DbType="NVarChar(50)")]
		public string YETKİLİ2
		{
			get
			{
				return this._YETKİLİ2;
			}
			set
			{
				if ((this._YETKİLİ2 != value))
				{
					this.OnYETKİLİ2Changing(value);
					this.SendPropertyChanging();
					this._YETKİLİ2 = value;
					this.SendPropertyChanged("YETKİLİ2");
					this.OnYETKİLİ2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKİLİ1EMAİLİ1", DbType="NVarChar(250)")]
		public string YETKİLİ1EMAİLİ1
		{
			get
			{
				return this._YETKİLİ1EMAİLİ1;
			}
			set
			{
				if ((this._YETKİLİ1EMAİLİ1 != value))
				{
					this.OnYETKİLİ1EMAİLİ1Changing(value);
					this.SendPropertyChanging();
					this._YETKİLİ1EMAİLİ1 = value;
					this.SendPropertyChanged("YETKİLİ1EMAİLİ1");
					this.OnYETKİLİ1EMAİLİ1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKİLİ2EMAİLİ2", DbType="NVarChar(250)")]
		public string YETKİLİ2EMAİLİ2
		{
			get
			{
				return this._YETKİLİ2EMAİLİ2;
			}
			set
			{
				if ((this._YETKİLİ2EMAİLİ2 != value))
				{
					this.OnYETKİLİ2EMAİLİ2Changing(value);
					this.SendPropertyChanging();
					this._YETKİLİ2EMAİLİ2 = value;
					this.SendPropertyChanged("YETKİLİ2EMAİLİ2");
					this.OnYETKİLİ2EMAİLİ2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARİHAREKETLERİ")]
	public partial class TBL_CARİHAREKETLERİ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CARİID;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _BORC;
		
		private System.Nullable<decimal> _ALACAK;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _TARİH;
		
		private string _TİPİ;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
		private System.Nullable<int> _EVRAKID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARİIDChanging(System.Nullable<int> value);
    partial void OnCARİIDChanged();
    partial void OnEVRAKTURUChanging(string value);
    partial void OnEVRAKTURUChanged();
    partial void OnBORCChanging(System.Nullable<int> value);
    partial void OnBORCChanged();
    partial void OnALACAKChanging(System.Nullable<decimal> value);
    partial void OnALACAKChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnTARİHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARİHChanged();
    partial void OnTİPİChanging(string value);
    partial void OnTİPİChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    partial void OnEVRAKIDChanging(System.Nullable<int> value);
    partial void OnEVRAKIDChanged();
    #endregion
		
		public TBL_CARİHAREKETLERİ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİID", DbType="Int")]
		public System.Nullable<int> CARİID
		{
			get
			{
				return this._CARİID;
			}
			set
			{
				if ((this._CARİID != value))
				{
					this.OnCARİIDChanging(value);
					this.SendPropertyChanging();
					this._CARİID = value;
					this.SendPropertyChanged("CARİID");
					this.OnCARİIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this.OnEVRAKTURUChanging(value);
					this.SendPropertyChanging();
					this._EVRAKTURU = value;
					this.SendPropertyChanged("EVRAKTURU");
					this.OnEVRAKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORC", DbType="Int")]
		public System.Nullable<int> BORC
		{
			get
			{
				return this._BORC;
			}
			set
			{
				if ((this._BORC != value))
				{
					this.OnBORCChanging(value);
					this.SendPropertyChanging();
					this._BORC = value;
					this.SendPropertyChanged("BORC");
					this.OnBORCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALACAK", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ALACAK
		{
			get
			{
				return this._ALACAK;
			}
			set
			{
				if ((this._ALACAK != value))
				{
					this.OnALACAKChanging(value);
					this.SendPropertyChanging();
					this._ALACAK = value;
					this.SendPropertyChanged("ALACAK");
					this.OnALACAKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARİH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARİH
		{
			get
			{
				return this._TARİH;
			}
			set
			{
				if ((this._TARİH != value))
				{
					this.OnTARİHChanging(value);
					this.SendPropertyChanging();
					this._TARİH = value;
					this.SendPropertyChanged("TARİH");
					this.OnTARİHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TİPİ", DbType="NVarChar(25)")]
		public string TİPİ
		{
			get
			{
				return this._TİPİ;
			}
			set
			{
				if ((this._TİPİ != value))
				{
					this.OnTİPİChanging(value);
					this.SendPropertyChanging();
					this._TİPİ = value;
					this.SendPropertyChanged("TİPİ");
					this.OnTİPİChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this.OnEVRAKIDChanging(value);
					this.SendPropertyChanging();
					this._EVRAKID = value;
					this.SendPropertyChanged("EVRAKID");
					this.OnEVRAKIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARİGRUPLARI")]
	public partial class TBL_CARİGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    #endregion
		
		public TBL_CARİGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BANKALAR")]
	public partial class TBL_BANKALAR
	{
		
		private int _ID;
		
		private string _HESAPNO;
		
		private string _IBAN;
		
		private string _BANKAADI;
		
		private string _HESAPADI;
		
		private string _SUBE;
		
		private string _TEL;
		
		private string _ADRES;
		
		private string _TEMSILCI;
		
		private string _TEMSILCIEMAIL;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
		public TBL_BANKALAR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this._HESAPNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this._IBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAADI", DbType="NVarChar(30)")]
		public string BANKAADI
		{
			get
			{
				return this._BANKAADI;
			}
			set
			{
				if ((this._BANKAADI != value))
				{
					this._BANKAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this._HESAPADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE", DbType="NVarChar(30)")]
		public string SUBE
		{
			get
			{
				return this._SUBE;
			}
			set
			{
				if ((this._SUBE != value))
				{
					this._SUBE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="NVarChar(16)")]
		public string TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this._TEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this._ADRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMSILCI", DbType="NVarChar(30)")]
		public string TEMSILCI
		{
			get
			{
				return this._TEMSILCI;
			}
			set
			{
				if ((this._TEMSILCI != value))
				{
					this._TEMSILCI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMSILCIEMAIL", DbType="NVarChar(150)")]
		public string TEMSILCIEMAIL
		{
			get
			{
				return this._TEMSILCIEMAIL;
			}
			set
			{
				if ((this._TEMSILCIEMAIL != value))
				{
					this._TEMSILCIEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this._SAVEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this._SAVEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this._EDITDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this._EDITUSER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BANKAHAREKETLERİ")]
	public partial class TBL_BANKAHAREKETLERİ
	{
		
		private int _ID;
		
		private System.Nullable<int> _BANKAID;
		
		private System.Nullable<int> _CARİID;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARİH;
		
		private string _EVRAKTÜRÜ;
		
		private System.Nullable<int> _EVRAKID;
		
		private string _GCKODU;
		
		private System.Nullable<decimal> _TUTAR;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTTİME;
		
		private System.Nullable<int> _EDİTUSER;
		
		public TBL_BANKAHAREKETLERİ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAID", DbType="Int")]
		public System.Nullable<int> BANKAID
		{
			get
			{
				return this._BANKAID;
			}
			set
			{
				if ((this._BANKAID != value))
				{
					this._BANKAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİID", DbType="Int")]
		public System.Nullable<int> CARİID
		{
			get
			{
				return this._CARİID;
			}
			set
			{
				if ((this._CARİID != value))
				{
					this._CARİID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(30)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this._BELGENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARİH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARİH
		{
			get
			{
				return this._TARİH;
			}
			set
			{
				if ((this._TARİH != value))
				{
					this._TARİH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTÜRÜ", DbType="NVarChar(30)")]
		public string EVRAKTÜRÜ
		{
			get
			{
				return this._EVRAKTÜRÜ;
			}
			set
			{
				if ((this._EVRAKTÜRÜ != value))
				{
					this._EVRAKTÜRÜ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this._EVRAKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKODU", DbType="NVarChar(1)")]
		public string GCKODU
		{
			get
			{
				return this._GCKODU;
			}
			set
			{
				if ((this._GCKODU != value))
				{
					this._GCKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this._TUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this._SAVEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this._SAVEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTTİME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTTİME
		{
			get
			{
				return this._EDİTTİME;
			}
			set
			{
				if ((this._EDİTTİME != value))
				{
					this._EDİTTİME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this._EDİTUSER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKADURUM")]
	public partial class VW_BANKADURUM
	{
		
		private int _ID;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private System.Nullable<decimal> _BAKİYE;
		
		public VW_BANKADURUM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKİYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKİYE
		{
			get
			{
				return this._BAKİYE;
			}
			set
			{
				if ((this._BAKİYE != value))
				{
					this._BAKİYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKAHAREKETLERİ")]
	public partial class VW_BANKAHAREKETLERİ
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _BANKAID;
		
		private System.Nullable<int> _CARİID;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARİH;
		
		private string _EVRAKTÜRÜ;
		
		private System.Nullable<int> _EVRAKID;
		
		private string _ACIKLAMA;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private string _HESAPADI;
		
		private string _HESAPNO;
		
		public VW_BANKAHAREKETLERİ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAID", DbType="Int")]
		public System.Nullable<int> BANKAID
		{
			get
			{
				return this._BANKAID;
			}
			set
			{
				if ((this._BANKAID != value))
				{
					this._BANKAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİID", DbType="Int")]
		public System.Nullable<int> CARİID
		{
			get
			{
				return this._CARİID;
			}
			set
			{
				if ((this._CARİID != value))
				{
					this._CARİID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(30)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this._BELGENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARİH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARİH
		{
			get
			{
				return this._TARİH;
			}
			set
			{
				if ((this._TARİH != value))
				{
					this._TARİH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTÜRÜ", DbType="NVarChar(30)")]
		public string EVRAKTÜRÜ
		{
			get
			{
				return this._EVRAKTÜRÜ;
			}
			set
			{
				if ((this._EVRAKTÜRÜ != value))
				{
					this._EVRAKTÜRÜ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this._EVRAKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this._HESAPADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this._HESAPNO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKALİSTESİ")]
	public partial class VW_BANKALİSTESİ
	{
		
		private int _ID;
		
		private string _HESAPNO;
		
		private string _IBAN;
		
		private string _BANKAADI;
		
		private string _HESAPADI;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private System.Nullable<decimal> _BAKİYE;
		
		public VW_BANKALİSTESİ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this._HESAPNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this._IBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAADI", DbType="NVarChar(30)")]
		public string BANKAADI
		{
			get
			{
				return this._BANKAADI;
			}
			set
			{
				if ((this._BANKAADI != value))
				{
					this._BANKAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this._HESAPADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKİYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKİYE
		{
			get
			{
				return this._BAKİYE;
			}
			set
			{
				if ((this._BAKİYE != value))
				{
					this._BAKİYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASADURUM")]
	public partial class VW_KASADURUM
	{
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private System.Nullable<decimal> _BAKİYE;
		
		public VW_KASADURUM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this._KASAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKİYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKİYE
		{
			get
			{
				return this._BAKİYE;
			}
			set
			{
				if ((this._BAKİYE != value))
				{
					this._BAKİYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASAHAREKETLERİ")]
	public partial class VW_KASAHAREKETLERİ
	{
		
		private int _ID;
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<int> _CARİID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _CARİKODU;
		
		private string _CARİADI;
		
		private string _BELGENO;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private System.Nullable<System.DateTime> _TARİH;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private string _ACIKLAMA;
		
		public VW_KASAHAREKETLERİ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this._KASAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİID", DbType="Int")]
		public System.Nullable<int> CARİID
		{
			get
			{
				return this._CARİID;
			}
			set
			{
				if ((this._CARİID != value))
				{
					this._CARİID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this._KASAKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this._KASAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİKODU", DbType="NVarChar(30)")]
		public string CARİKODU
		{
			get
			{
				return this._CARİKODU;
			}
			set
			{
				if ((this._CARİKODU != value))
				{
					this._CARİKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARİADI", DbType="NVarChar(30)")]
		public string CARİADI
		{
			get
			{
				return this._CARİADI;
			}
			set
			{
				if ((this._CARİADI != value))
				{
					this._CARİADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(50)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this._BELGENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this._EVRAKTURU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this._EVRAKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARİH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARİH
		{
			get
			{
				return this._TARİH;
			}
			set
			{
				if ((this._TARİH != value))
				{
					this._TARİH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASALİSTESİ")]
	public partial class VW_KASALİSTESİ
	{
		
		private int _ID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _ACİKLAMA;
		
		private System.Nullable<decimal> _GİRİS;
		
		private System.Nullable<decimal> _CİKİS;
		
		private System.Nullable<decimal> _BAKİYE;
		
		public VW_KASALİSTESİ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this._KASAKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this._KASAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACİKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACİKLAMA
		{
			get
			{
				return this._ACİKLAMA;
			}
			set
			{
				if ((this._ACİKLAMA != value))
				{
					this._ACİKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GİRİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GİRİS
		{
			get
			{
				return this._GİRİS;
			}
			set
			{
				if ((this._GİRİS != value))
				{
					this._GİRİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CİKİS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CİKİS
		{
			get
			{
				return this._CİKİS;
			}
			set
			{
				if ((this._CİKİS != value))
				{
					this._CİKİS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKİYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKİYE
		{
			get
			{
				return this._BAKİYE;
			}
			set
			{
				if ((this._BAKİYE != value))
				{
					this._BAKİYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KULLANICILAR")]
	public partial class TBL_KULLANICILAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KULLANICI;
		
		private string _SİFRE;
		
		private string _ISIM;
		
		private string _SOYISIM;
		
		private string _AKTİF;
		
		private System.Nullable<bool> _KODU;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<System.DateTime> _EDİTTİME;
		
		private System.Nullable<System.DateTime> _LASTLOGİN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKULLANICIChanging(string value);
    partial void OnKULLANICIChanged();
    partial void OnSİFREChanging(string value);
    partial void OnSİFREChanged();
    partial void OnISIMChanging(string value);
    partial void OnISIMChanged();
    partial void OnSOYISIMChanging(string value);
    partial void OnSOYISIMChanged();
    partial void OnAKTİFChanging(string value);
    partial void OnAKTİFChanged();
    partial void OnKODUChanging(System.Nullable<bool> value);
    partial void OnKODUChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnEDİTTİMEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTTİMEChanged();
    partial void OnLASTLOGİNChanging(System.Nullable<System.DateTime> value);
    partial void OnLASTLOGİNChanged();
    #endregion
		
		public TBL_KULLANICILAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICI", DbType="NVarChar(50)")]
		public string KULLANICI
		{
			get
			{
				return this._KULLANICI;
			}
			set
			{
				if ((this._KULLANICI != value))
				{
					this.OnKULLANICIChanging(value);
					this.SendPropertyChanging();
					this._KULLANICI = value;
					this.SendPropertyChanged("KULLANICI");
					this.OnKULLANICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SİFRE", DbType="NVarChar(50)")]
		public string SİFRE
		{
			get
			{
				return this._SİFRE;
			}
			set
			{
				if ((this._SİFRE != value))
				{
					this.OnSİFREChanging(value);
					this.SendPropertyChanging();
					this._SİFRE = value;
					this.SendPropertyChanged("SİFRE");
					this.OnSİFREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISIM", DbType="NVarChar(50)")]
		public string ISIM
		{
			get
			{
				return this._ISIM;
			}
			set
			{
				if ((this._ISIM != value))
				{
					this.OnISIMChanging(value);
					this.SendPropertyChanging();
					this._ISIM = value;
					this.SendPropertyChanged("ISIM");
					this.OnISIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOYISIM", DbType="NVarChar(50)")]
		public string SOYISIM
		{
			get
			{
				return this._SOYISIM;
			}
			set
			{
				if ((this._SOYISIM != value))
				{
					this.OnSOYISIMChanging(value);
					this.SendPropertyChanging();
					this._SOYISIM = value;
					this.SendPropertyChanged("SOYISIM");
					this.OnSOYISIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKTİF", DbType="NVarChar(50)")]
		public string AKTİF
		{
			get
			{
				return this._AKTİF;
			}
			set
			{
				if ((this._AKTİF != value))
				{
					this.OnAKTİFChanging(value);
					this.SendPropertyChanging();
					this._AKTİF = value;
					this.SendPropertyChanged("AKTİF");
					this.OnAKTİFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODU", DbType="Bit")]
		public System.Nullable<bool> KODU
		{
			get
			{
				return this._KODU;
			}
			set
			{
				if ((this._KODU != value))
				{
					this.OnKODUChanging(value);
					this.SendPropertyChanging();
					this._KODU = value;
					this.SendPropertyChanged("KODU");
					this.OnKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTTİME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTTİME
		{
			get
			{
				return this._EDİTTİME;
			}
			set
			{
				if ((this._EDİTTİME != value))
				{
					this.OnEDİTTİMEChanging(value);
					this.SendPropertyChanging();
					this._EDİTTİME = value;
					this.SendPropertyChanged("EDİTTİME");
					this.OnEDİTTİMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTLOGİN", DbType="DateTime")]
		public System.Nullable<System.DateTime> LASTLOGİN
		{
			get
			{
				return this._LASTLOGİN;
			}
			set
			{
				if ((this._LASTLOGİN != value))
				{
					this.OnLASTLOGİNChanging(value);
					this.SendPropertyChanging();
					this._LASTLOGİN = value;
					this.SendPropertyChanged("LASTLOGİN");
					this.OnLASTLOGİNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
